---
title: "Plots"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
---


```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
install.packages("plotly")
library(plotly)

library(tidyverse)
library(httr)
library(jsonlite)

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = get_all_inspections(url) %>%
  bind_rows() 
```

```{r}
#filter data for most current inspection date
#group by ratings
#make plots 


```